//CREATE BOOKING
POST http://localhost:3000/bookings/create
Content-Type: application/json

{
  "name": "Alen",
  "Date": "127462359218",
  "amount": "2",
  "table": "12",
  "sitting": "1"
}

###
//CANCEL BOOKING
POST http://localhost:3000/bookings/cancel
Content-Type: application/json

{
  "shortId": "ut5rLn",
  "name": "Alen"
}